disable ligatures in monospace code blocks.
adobe/parliament-client-template pull request #414
Opened 2024-02-09 01:45 UTC by sparecycles

## Description

turns off font ligatures in code blocks.

## Related Issue

#413

## Motivation and Context

It looks bad and is harder to read.

## How Has This Been Tested?

In the brower, via dev-tools on the class declaration in question.

## Screenshots (if appropriate):

![image](https://github.com/adobe/parliament-client-template/assets/719818/04c498ec-8875-4a37-be14-f78c83d0c872)

Note `font-variant-ligatures: no-common-ligatures` does not help.
![image](https://github.com/adobe/parliament-client-template/assets/719818/0730ddd9-e9de-4a4e-9bcc-60356fa83344)

(also note the screen-shot text was also edited in dev-tools, I don't remember where I found the original issue).

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed. 🤞

2024-02-09 04:49 UTC, sparecycles commented
I don't understand the CI failure, if it's checking out [pull/414/merge](https://github.com/adobe/parliament-client-template/tree/pull/414/merge)
<img width="614" alt="image" src="https://github.com/adobe/parliament-client-template/assets/719818/92917b53-4162-4a8a-9f79-464b7b4c06ca">

then it shouldn't need to pull the branch specifically
<img width="912" alt="image" src="https://github.com/adobe/parliament-client-template/assets/719818/5b20acc3-ed09-4b53-8330-12b0d4d7cd46">

and it can't find it because it's in my fork.  Does this project not accept pull requests from forked repos?

2024-02-15 00:04 UTC, solimant requested changes

2024-02-15 00:04 UTC, solimant commented on src/components/layout.css
> +  font-feature-settings: "liga" 0;
```suggestion
  font-feature-settings: "liga" 0;
  white-space: pre-wrap !important;
```

2024-02-15 00:05 UTC, solimant approved these changes
Thank you 🙏🏼

2024-02-15 00:09 UTC, merged